# Week2授業前課題3 行列積のスクラッチ

In [9]:
import numpy as np

## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

<pre>
A = -1,  2,  3　   B = 0, 2,  1
     4, -5 , 6　　     0, 2, -8
     7,  8, -9         2, 9, -1
    
AxB = (-1x0)+( 2x0)+( 3x2),   (-1x2)+( 2x2)+( 3x9),   (-1x1)+( 2x(-8))+( 3x(-1))  
      ( 4x0)+(-5x0)+( 6x2),   ( 4x2)+(-5x2)+( 6x9),   ( 4x1)+(-5x(-8))+( 6x(-1))  
      ( 7x0)+( 8x0)+(-9x2),   ( 7x2)+( 8x2)+(-9x9),   ( 7x1)+( 8x(-8))+(-9x(-1))  
      
AxB = 0+0+ 6, -2+ 4+27, -1-16-3  
      0+0+12,  8-10+54,  4+40-6  
      0+0-18, 14+16-81,  7-64+9  
      
AxB =   6,    29,  -20  
       12,    52,   38  
      -18,   -51,  -48    

## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

In [10]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [11]:
ab = np.matmul(a_ndarray, b_ndarray)
ab

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。  
この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [12]:
A = a_ndarray
B = b_ndarray

result = 0
result_list = []
for n in range(3):
    for j in range(3):
        for i in range(3):
            seki = A[n, i] * B[i, j]
            result += seki
        result_list.append(result)
        result = 0
        
result_array = np.array(result_list)
result_array_33 = result_array.reshape(3,3)
print(result_array_33)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。  
インデックスiやjを1増やすと、次の行や列に移ることができます。

In [13]:
A = a_ndarray
B = b_ndarray

def multi(A, B):
    result = 0
    result_list = []
    for n in range(A.shape[0]):
        for j in range(B.shape[1]):
            for i in range(A.shape[0]):
                seki = A[n, i] * B[i, j]
                result += seki
            result_list.append(result)
            result = 0
    replace_result = np.array(result_list)
    return  replace_result.reshape(A.shape[0], B.shape[1])

## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。  
この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [14]:
def multi_2(A, B):
    result = 0
    result_list = []
    if A.shape[1] == B.shape[0]:
        for n in range(A.shape[0]):
            for j in range(B.shape[1]):
                for i in range(A.shape[0]):
                    seki = A[n, i] * B[i, j]
                    result += seki
                result_list.append(result)
                result = 0
        replace_result = np.array(result_list)
        return  replace_result.reshape(A.shape[0], B.shape[1])
    else:
        print("定義できません")

In [15]:
A = a_ndarray
B = b_ndarray

D = np.array([[-1, 2, 3],
             [4, -5, 6]])
E = np.array([[-9, 8, 7],
             [6, -5, 4]])
print(multi_2(A, B))
print(multi_2(D, E))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
定義できません
None


## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [16]:
E_T = np.transpose(E)
multi_2(D, E_T)

array([[ 25, -16],
       [-76,  49]])